jobs:
- job: 'Test'
  strategy:
    matrix:
      LinuxPython36:
        python.version: '3.6'
        image.name: 'ubuntu-18.04'
      LinuxPython37:
        python.version: '3.7'
        image.name: 'ubuntu-18.04'
      LinuxPython38:
        python.version: '3.8'
        image.name: 'ubuntu-18.04'
      WindowsPython36:
        python.version: '3.6'
        image.name: 'windows-2019'
      WindowsPython37:
        python.version: '3.7'
        image.name: 'windows-2019'
      WindowsPython38:
        python.version: '3.8'
        image.name: 'windows-2019'
      MacPython36:
        python.version: '3.6'
        image.name: 'macOS-10.14'
      MacPython37:
        python.version: '3.7'
        image.name: 'macOS-10.14'
      MacPython38:
        python.version: '3.8'
        image.name: 'macOS-10.14'
    maxParallel: 9
  pool:
    vmImage: '$(image.name)'
  steps:
    - task: UsePythonVersion@0
      condition: succeeded()
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'
    - script: python -m pip install --upgrade pip setuptools wheel
      condition: succeeded()
      displayName: 'Install tools'
    - script: python -m pip install pytest pytest-cov numpy pandas
      condition: succeeded()
      displayName: 'Install test requirements'
    - script: python -m pip install torch==1.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
      condition: succeeded()
      displayName: 'Install pytorch'      
    - script: |
        python -m pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      displayName: 'Run pytest'
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '**/test-*.xml'
        testRunTitle: 'Publish test results for Python $(python.version) at $(image.name)'
      displayName: 'Publish test results'
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
        reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
      displayName: 'Publish test coverage results'
